{
  "name": "chapter-10-handling-errors",
  "version": "1.0.0",
  "description": "",
  "main": "async-try-catch.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
